"""drop facing from source_installations

Revision ID: 11d04c5fc2b9
Revises: 5af12c11469f
Create Date: 2026-07-23 16:05:31.571676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11d04c5fc2b9'
down_revision: Union[str, None] = '5af12c11469f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_installations', 'facing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_installations', sa.Column('facing', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
