"""add number_subruns to runs

Revision ID: 11f69c384c47
Revises: 5a8a74844dab
Create Date: 2026-07-22 14:17:11.420366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '11f69c384c47'
down_revision: Union[str, None] = '5a8a74844dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('number_subruns', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'number_subruns')
    # ### end Alembic commands ###
