"""move preamp/fet wiring to pixels

Revision ID: 134d9680eb84
Revises: 11f69c384c47
Create Date: 2026-07-22 15:02:04.127072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '134d9680eb84'
down_revision: Union[str, None] = '11f69c384c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pixels', sa.Column('preamp', sa.String(length=50), nullable=True))
    op.add_column('pixels', sa.Column('fet', sa.String(length=50), nullable=True))
    op.drop_column('run_pixels', 'fet')
    op.drop_column('run_pixels', 'preamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_pixels', sa.Column('preamp', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('run_pixels', sa.Column('fet', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('pixels', 'fet')
    op.drop_column('pixels', 'preamp')
    # ### end Alembic commands ###
