"""drop threshold from run_pixels

Revision ID: 176240dc266a
Revises: 50b948f82c29
Create Date: 2026-07-22 16:43:19.754143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '176240dc266a'
down_revision: Union[str, None] = '50b948f82c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_pixels', 'threshold')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_pixels', sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
