"""spectrum fit uncertainty and multi-fit columns

Revision ID: 19e76b0eeb63
Revises: 39e722d52585
Create Date: 2026-07-30 17:12:50.009863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '19e76b0eeb63'
down_revision: Union[str, None] = '39e722d52585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spectrum_fits', sa.Column('label', sa.String(length=50), nullable=True))
    op.add_column('spectrum_fits', sa.Column('fit_range_low', sa.Integer(), nullable=True))
    op.add_column('spectrum_fits', sa.Column('fit_range_high', sa.Integer(), nullable=True))
    op.add_column('spectrum_fits', sa.Column('n_peaks', sa.Integer(), nullable=True))
    op.add_column('spectrum_fits', sa.Column('reduced_chi2', sa.Float(), nullable=True))
    op.add_column('spectrum_fits', sa.Column('success', sa.Boolean(), nullable=True))
    op.add_column('spectrum_fits', sa.Column('var_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('spectrum_fits', sa.Column('covariance', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('spectrum_fits', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spectrum_fits', 'config')
    op.drop_column('spectrum_fits', 'covariance')
    op.drop_column('spectrum_fits', 'var_names')
    op.drop_column('spectrum_fits', 'success')
    op.drop_column('spectrum_fits', 'reduced_chi2')
    op.drop_column('spectrum_fits', 'n_peaks')
    op.drop_column('spectrum_fits', 'fit_range_high')
    op.drop_column('spectrum_fits', 'fit_range_low')
    op.drop_column('spectrum_fits', 'label')
    # ### end Alembic commands ###
