"""initial schema

Revision ID: 32d4cad502f6
Revises: 
Create Date: 2026-07-21 15:50:11.677348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '32d4cad502f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isotopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pixels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pixel_number', sa.Integer(), nullable=False),
    sa.Column('detector', sa.String(length=10), nullable=False),
    sa.CheckConstraint("(detector = 'upper' AND pixel_number <= 127) OR (detector = 'lower' AND pixel_number >= 1001)", name='ck_pixels_detector_matches_number'),
    sa.CheckConstraint('pixel_number BETWEEN 1 AND 127 OR pixel_number BETWEEN 1001 AND 1127', name='ck_pixels_number_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pixels_pixel_number'), 'pixels', ['pixel_number'], unique=True)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('udet_bias', sa.Float(), nullable=True),
    sa.Column('ldet_bias', sa.Float(), nullable=True),
    sa.Column('hv', sa.Float(), nullable=True),
    sa.Column('main', sa.Float(), nullable=True),
    sa.Column('udet', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('linear_position', sa.Float(), nullable=True),
    sa.Column('horizontal_position', sa.Float(), nullable=True),
    sa.Column('exb', sa.Float(), nullable=True),
    sa.Column('udet_armor', sa.Float(), nullable=True),
    sa.Column('ldet_armor', sa.Float(), nullable=True),
    sa.Column('udet_ring', sa.Float(), nullable=True),
    sa.Column('ldet_ring', sa.Float(), nullable=True),
    sa.Column('udet_leakage', sa.Float(), nullable=True),
    sa.Column('ldet_leakage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_run_number'), 'runs', ['run_number'], unique=True)
    op.create_table('isotope_peaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isotope_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['isotope_id'], ['isotopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isotope_id', 'label')
    )
    op.create_index(op.f('ix_isotope_peaks_isotope_id'), 'isotope_peaks', ['isotope_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isotope_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['isotope_id'], ['isotopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_id')
    )
    op.create_index(op.f('ix_sources_isotope_id'), 'sources', ['isotope_id'], unique=False)
    op.create_table('peak_energies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isotope_peak_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('energy_kev', sa.Float(), nullable=False),
    sa.Column('energy_error_kev', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isotope_peak_id'], ['isotope_peaks.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peak_energies_isotope_peak_id'), 'peak_energies', ['isotope_peak_id'], unique=False)
    op.create_index(op.f('ix_peak_energies_source_id'), 'peak_energies', ['source_id'], unique=False)
    op.create_table('run_pixels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('pixel_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('board_channel', sa.Integer(), nullable=True),
    sa.Column('preamp', sa.String(length=50), nullable=True),
    sa.Column('fet', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pixel_id'], ['pixels.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'board_channel'),
    sa.UniqueConstraint('run_id', 'pixel_id')
    )
    op.create_index(op.f('ix_run_pixels_pixel_id'), 'run_pixels', ['pixel_id'], unique=False)
    op.create_index(op.f('ix_run_pixels_run_id'), 'run_pixels', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_pixels_source_id'), 'run_pixels', ['source_id'], unique=False)
    op.create_table('trap_filter_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_pixel_id', sa.Integer(), nullable=False),
    sa.Column('trap_rise', sa.Float(), nullable=True),
    sa.Column('trap_flattop', sa.Float(), nullable=True),
    sa.Column('trap_falltime', sa.Float(), nullable=True),
    sa.Column('energies', postgresql.ARRAY(sa.DOUBLE_PRECISION()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_pixel_id'], ['run_pixels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trap_filter_outputs_run_pixel_id'), 'trap_filter_outputs', ['run_pixel_id'], unique=False)
    op.create_table('spectrum_fits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trap_filter_output_id', sa.Integer(), nullable=False),
    sa.Column('chi2', sa.Float(), nullable=True),
    sa.Column('ndf', sa.Integer(), nullable=True),
    sa.Column('pars', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('par_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trap_filter_output_id'], ['trap_filter_outputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spectrum_fits_trap_filter_output_id'), 'spectrum_fits', ['trap_filter_output_id'], unique=False)
    op.create_table('calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spectrum_fit_id', sa.Integer(), nullable=False),
    sa.Column('run_pixel_id', sa.Integer(), nullable=False),
    sa.Column('calibration_type', sa.String(length=20), nullable=False),
    sa.Column('constant_term', sa.Float(), nullable=True),
    sa.Column('constant_error', sa.Float(), nullable=True),
    sa.Column('linear_term', sa.Float(), nullable=True),
    sa.Column('linear_error', sa.Float(), nullable=True),
    sa.Column('quadratic_term', sa.Float(), nullable=True),
    sa.Column('quadratic_error', sa.Float(), nullable=True),
    sa.Column('chi2', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_pixel_id'], ['run_pixels.id'], ),
    sa.ForeignKeyConstraint(['spectrum_fit_id'], ['spectrum_fits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calibrations_one_current', 'calibrations', ['run_pixel_id', 'calibration_type'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_index(op.f('ix_calibrations_run_pixel_id'), 'calibrations', ['run_pixel_id'], unique=False)
    op.create_index(op.f('ix_calibrations_spectrum_fit_id'), 'calibrations', ['spectrum_fit_id'], unique=False)
    op.create_table('peaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spectrum_fit_id', sa.Integer(), nullable=False),
    sa.Column('isotope_peak_id', sa.Integer(), nullable=True),
    sa.Column('centroid_adc', sa.Float(), nullable=False),
    sa.Column('centroid_error_adc', sa.Float(), nullable=True),
    sa.Column('sigma_adc', sa.Float(), nullable=True),
    sa.Column('sigma_error_adc', sa.Float(), nullable=True),
    sa.Column('amplitude', sa.Float(), nullable=True),
    sa.Column('amplitude_error', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['isotope_peak_id'], ['isotope_peaks.id'], ),
    sa.ForeignKeyConstraint(['spectrum_fit_id'], ['spectrum_fits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peaks_isotope_peak_id'), 'peaks', ['isotope_peak_id'], unique=False)
    op.create_index(op.f('ix_peaks_spectrum_fit_id'), 'peaks', ['spectrum_fit_id'], unique=False)
    op.create_table('calibration_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calibration_id', sa.Integer(), nullable=False),
    sa.Column('peak_id', sa.Integer(), nullable=False),
    sa.Column('peak_energy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calibration_id'], ['calibrations.id'], ),
    sa.ForeignKeyConstraint(['peak_energy_id'], ['peak_energies.id'], ),
    sa.ForeignKeyConstraint(['peak_id'], ['peaks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calibration_id', 'peak_id')
    )
    op.create_index(op.f('ix_calibration_points_calibration_id'), 'calibration_points', ['calibration_id'], unique=False)
    op.create_index(op.f('ix_calibration_points_peak_energy_id'), 'calibration_points', ['peak_energy_id'], unique=False)
    op.create_index(op.f('ix_calibration_points_peak_id'), 'calibration_points', ['peak_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calibration_points_peak_id'), table_name='calibration_points')
    op.drop_index(op.f('ix_calibration_points_peak_energy_id'), table_name='calibration_points')
    op.drop_index(op.f('ix_calibration_points_calibration_id'), table_name='calibration_points')
    op.drop_table('calibration_points')
    op.drop_index(op.f('ix_peaks_spectrum_fit_id'), table_name='peaks')
    op.drop_index(op.f('ix_peaks_isotope_peak_id'), table_name='peaks')
    op.drop_table('peaks')
    op.drop_index(op.f('ix_calibrations_spectrum_fit_id'), table_name='calibrations')
    op.drop_index(op.f('ix_calibrations_run_pixel_id'), table_name='calibrations')
    op.drop_index('ix_calibrations_one_current', table_name='calibrations', postgresql_where=sa.text('is_current'))
    op.drop_table('calibrations')
    op.drop_index(op.f('ix_spectrum_fits_trap_filter_output_id'), table_name='spectrum_fits')
    op.drop_table('spectrum_fits')
    op.drop_index(op.f('ix_trap_filter_outputs_run_pixel_id'), table_name='trap_filter_outputs')
    op.drop_table('trap_filter_outputs')
    op.drop_index(op.f('ix_run_pixels_source_id'), table_name='run_pixels')
    op.drop_index(op.f('ix_run_pixels_run_id'), table_name='run_pixels')
    op.drop_index(op.f('ix_run_pixels_pixel_id'), table_name='run_pixels')
    op.drop_table('run_pixels')
    op.drop_index(op.f('ix_peak_energies_source_id'), table_name='peak_energies')
    op.drop_index(op.f('ix_peak_energies_isotope_peak_id'), table_name='peak_energies')
    op.drop_table('peak_energies')
    op.drop_index(op.f('ix_sources_isotope_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_isotope_peaks_isotope_id'), table_name='isotope_peaks')
    op.drop_table('isotope_peaks')
    op.drop_index(op.f('ix_runs_run_number'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_pixels_pixel_number'), table_name='pixels')
    op.drop_table('pixels')
    op.drop_table('isotopes')
    # ### end Alembic commands ###
