"""source holder on installations

Revision ID: 39e722d52585
Revises: f1cff52b4eab
Create Date: 2026-07-30 14:19:04.301493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39e722d52585'
down_revision: Union[str, None] = 'f1cff52b4eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_installations', sa.Column('holder', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_installations', 'holder')
    # ### end Alembic commands ###
