"""trap output label and source_file

Revision ID: 50b948f82c29
Revises: 134d9680eb84
Create Date: 2026-07-22 15:19:53.507339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50b948f82c29'
down_revision: Union[str, None] = '134d9680eb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trap_filter_outputs', sa.Column('label', sa.String(length=50), nullable=True))
    op.add_column('trap_filter_outputs', sa.Column('source_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trap_filter_outputs', 'source_file')
    op.drop_column('trap_filter_outputs', 'label')
    # ### end Alembic commands ###
