"""calibrations reference their trap_filter_output

Revision ID: 571a40f12016
Revises: db80d607e393
Create Date: 2026-08-03 10:48:40.314731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '571a40f12016'
down_revision: Union[str, None] = 'db80d607e393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrations', sa.Column('trap_filter_output_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_calibrations_trap_filter_output_id'), 'calibrations', ['trap_filter_output_id'], unique=False)
    op.create_foreign_key(None, 'calibrations', 'trap_filter_outputs', ['trap_filter_output_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calibrations', type_='foreignkey')
    op.drop_index(op.f('ix_calibrations_trap_filter_output_id'), table_name='calibrations')
    op.drop_column('calibrations', 'trap_filter_output_id')
    # ### end Alembic commands ###
