"""source_installations table

Revision ID: 5af12c11469f
Revises: 5bbe78201969
Create Date: 2026-07-23 13:39:40.656584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5af12c11469f'
down_revision: Union[str, None] = '5bbe78201969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('installed_on', sa.Date(), nullable=False),
    sa.Column('removed_on', sa.Date(), nullable=True),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('facing', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_installations_source_id'), 'source_installations', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_installations_source_id'), table_name='source_installations')
    op.drop_table('source_installations')
    # ### end Alembic commands ###
