"""source label and serial_number

Revision ID: 5bbe78201969
Revises: 176240dc266a
Create Date: 2026-07-23 13:19:22.764336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5bbe78201969'
down_revision: Union[str, None] = '176240dc266a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('label', sa.String(length=50), nullable=False))
    op.add_column('sources', sa.Column('serial_number', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('sources_manufacturer_id_key'), 'sources', type_='unique')
    op.create_unique_constraint(None, 'sources', ['label'])
    op.create_unique_constraint(None, 'sources', ['serial_number'])
    op.drop_column('sources', 'manufacturer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('manufacturer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sources', type_='unique')
    op.drop_constraint(None, 'sources', type_='unique')
    op.create_unique_constraint(op.f('sources_manufacturer_id_key'), 'sources', ['manufacturer_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('sources', 'serial_number')
    op.drop_column('sources', 'label')
    # ### end Alembic commands ###
