"""calibrations: drop spectrum_fit_id, add fit-quality and covariance columns

Revision ID: 9ca472d287a3
Revises: a43115749c9e
Create Date: 2026-07-30 17:54:47.976634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9ca472d287a3'
down_revision: Union[str, None] = 'a43115749c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrations', sa.Column('label', sa.String(length=50), nullable=True))
    op.add_column('calibrations', sa.Column('ndf', sa.Integer(), nullable=True))
    op.add_column('calibrations', sa.Column('reduced_chi2', sa.Float(), nullable=True))
    op.add_column('calibrations', sa.Column('success', sa.Boolean(), nullable=True))
    op.add_column('calibrations', sa.Column('var_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('calibrations', sa.Column('covariance', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('calibrations', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_calibrations_spectrum_fit_id'), table_name='calibrations')
    op.drop_constraint(op.f('calibrations_spectrum_fit_id_fkey'), 'calibrations', type_='foreignkey')
    op.drop_column('calibrations', 'spectrum_fit_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrations', sa.Column('spectrum_fit_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('calibrations_spectrum_fit_id_fkey'), 'calibrations', 'spectrum_fits', ['spectrum_fit_id'], ['id'])
    op.create_index(op.f('ix_calibrations_spectrum_fit_id'), 'calibrations', ['spectrum_fit_id'], unique=False)
    op.drop_column('calibrations', 'config')
    op.drop_column('calibrations', 'covariance')
    op.drop_column('calibrations', 'var_names')
    op.drop_column('calibrations', 'success')
    op.drop_column('calibrations', 'reduced_chi2')
    op.drop_column('calibrations', 'ndf')
    op.drop_column('calibrations', 'label')
    # ### end Alembic commands ###
