"""rename peak tables for adc/kev clarity

Revision ID: a43115749c9e
Revises: 19e76b0eeb63
Create Date: 2026-07-30 17:35:45.497916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a43115749c9e'
down_revision: Union[str, None] = '19e76b0eeb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('isotope_decay_energies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isotope_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['isotope_id'], ['isotopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isotope_id', 'label')
    )
    op.create_index(op.f('ix_isotope_decay_energies_isotope_id'), 'isotope_decay_energies', ['isotope_id'], unique=False)
    op.create_table('kev_peaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isotope_decay_energy_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('energy_kev', sa.Float(), nullable=False),
    sa.Column('energy_error_kev', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isotope_decay_energy_id'], ['isotope_decay_energies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kev_peaks_isotope_decay_energy_id'), 'kev_peaks', ['isotope_decay_energy_id'], unique=False)
    op.create_index(op.f('ix_kev_peaks_source_id'), 'kev_peaks', ['source_id'], unique=False)
    op.create_table('adc_peaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spectrum_fit_id', sa.Integer(), nullable=False),
    sa.Column('isotope_decay_energy_id', sa.Integer(), nullable=True),
    sa.Column('centroid_adc', sa.Float(), nullable=False),
    sa.Column('centroid_error_adc', sa.Float(), nullable=True),
    sa.Column('sigma_adc', sa.Float(), nullable=True),
    sa.Column('sigma_error_adc', sa.Float(), nullable=True),
    sa.Column('amplitude', sa.Float(), nullable=True),
    sa.Column('amplitude_error', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['isotope_decay_energy_id'], ['isotope_decay_energies.id'], ),
    sa.ForeignKeyConstraint(['spectrum_fit_id'], ['spectrum_fits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adc_peaks_isotope_decay_energy_id'), 'adc_peaks', ['isotope_decay_energy_id'], unique=False)
    op.create_index(op.f('ix_adc_peaks_spectrum_fit_id'), 'adc_peaks', ['spectrum_fit_id'], unique=False)
    # calibration_points' FKs into the old tables must go BEFORE the old
    # tables are dropped (autogenerate ordered these wrong).
    op.drop_constraint(op.f('calibration_points_peak_energy_id_fkey'), 'calibration_points', type_='foreignkey')
    op.drop_constraint(op.f('calibration_points_peak_id_fkey'), 'calibration_points', type_='foreignkey')
    op.drop_index(op.f('ix_peaks_isotope_peak_id'), table_name='peaks')
    op.drop_index(op.f('ix_peaks_spectrum_fit_id'), table_name='peaks')
    op.drop_table('peaks')
    op.drop_index(op.f('ix_peak_energies_isotope_peak_id'), table_name='peak_energies')
    op.drop_index(op.f('ix_peak_energies_source_id'), table_name='peak_energies')
    op.drop_table('peak_energies')
    op.drop_index(op.f('ix_isotope_peaks_isotope_id'), table_name='isotope_peaks')
    op.drop_table('isotope_peaks')
    op.add_column('calibration_points', sa.Column('adc_peak_id', sa.Integer(), nullable=False))
    op.add_column('calibration_points', sa.Column('kev_peak_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('calibration_points_calibration_id_peak_id_key'), 'calibration_points', type_='unique')
    op.drop_index(op.f('ix_calibration_points_peak_energy_id'), table_name='calibration_points')
    op.drop_index(op.f('ix_calibration_points_peak_id'), table_name='calibration_points')
    op.create_index(op.f('ix_calibration_points_adc_peak_id'), 'calibration_points', ['adc_peak_id'], unique=False)
    op.create_index(op.f('ix_calibration_points_kev_peak_id'), 'calibration_points', ['kev_peak_id'], unique=False)
    op.create_unique_constraint(None, 'calibration_points', ['calibration_id', 'adc_peak_id'])
    op.create_foreign_key(None, 'calibration_points', 'kev_peaks', ['kev_peak_id'], ['id'])
    op.create_foreign_key(None, 'calibration_points', 'adc_peaks', ['adc_peak_id'], ['id'])
    op.drop_column('calibration_points', 'peak_energy_id')
    op.drop_column('calibration_points', 'peak_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibration_points', sa.Column('peak_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('calibration_points', sa.Column('peak_energy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'calibration_points', type_='foreignkey')
    op.drop_constraint(None, 'calibration_points', type_='foreignkey')
    op.create_foreign_key(op.f('calibration_points_peak_id_fkey'), 'calibration_points', 'peaks', ['peak_id'], ['id'])
    op.create_foreign_key(op.f('calibration_points_peak_energy_id_fkey'), 'calibration_points', 'peak_energies', ['peak_energy_id'], ['id'])
    op.drop_constraint(None, 'calibration_points', type_='unique')
    op.drop_index(op.f('ix_calibration_points_kev_peak_id'), table_name='calibration_points')
    op.drop_index(op.f('ix_calibration_points_adc_peak_id'), table_name='calibration_points')
    op.create_index(op.f('ix_calibration_points_peak_id'), 'calibration_points', ['peak_id'], unique=False)
    op.create_index(op.f('ix_calibration_points_peak_energy_id'), 'calibration_points', ['peak_energy_id'], unique=False)
    op.create_unique_constraint(op.f('calibration_points_calibration_id_peak_id_key'), 'calibration_points', ['calibration_id', 'peak_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('calibration_points', 'kev_peak_id')
    op.drop_column('calibration_points', 'adc_peak_id')
    op.create_table('isotope_peaks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isotope_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['isotope_id'], ['isotopes.id'], name=op.f('isotope_peaks_isotope_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('isotope_peaks_pkey')),
    sa.UniqueConstraint('isotope_id', 'label', name=op.f('isotope_peaks_isotope_id_label_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_isotope_peaks_isotope_id'), 'isotope_peaks', ['isotope_id'], unique=False)
    op.create_table('peak_energies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('isotope_peak_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_kev', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('energy_error_kev', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['isotope_peak_id'], ['isotope_peaks.id'], name=op.f('peak_energies_isotope_peak_id_fkey')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('peak_energies_source_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('peak_energies_pkey'))
    )
    op.create_index(op.f('ix_peak_energies_source_id'), 'peak_energies', ['source_id'], unique=False)
    op.create_index(op.f('ix_peak_energies_isotope_peak_id'), 'peak_energies', ['isotope_peak_id'], unique=False)
    op.create_table('peaks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('spectrum_fit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('isotope_peak_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('centroid_adc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('centroid_error_adc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sigma_adc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sigma_error_adc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amplitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amplitude_error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['isotope_peak_id'], ['isotope_peaks.id'], name=op.f('peaks_isotope_peak_id_fkey')),
    sa.ForeignKeyConstraint(['spectrum_fit_id'], ['spectrum_fits.id'], name=op.f('peaks_spectrum_fit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('peaks_pkey'))
    )
    op.create_index(op.f('ix_peaks_spectrum_fit_id'), 'peaks', ['spectrum_fit_id'], unique=False)
    op.create_index(op.f('ix_peaks_isotope_peak_id'), 'peaks', ['isotope_peak_id'], unique=False)
    op.drop_index(op.f('ix_adc_peaks_spectrum_fit_id'), table_name='adc_peaks')
    op.drop_index(op.f('ix_adc_peaks_isotope_decay_energy_id'), table_name='adc_peaks')
    op.drop_table('adc_peaks')
    op.drop_index(op.f('ix_kev_peaks_source_id'), table_name='kev_peaks')
    op.drop_index(op.f('ix_kev_peaks_isotope_decay_energy_id'), table_name='kev_peaks')
    op.drop_table('kev_peaks')
    op.drop_index(op.f('ix_isotope_decay_energies_isotope_id'), table_name='isotope_decay_energies')
    op.drop_table('isotope_decay_energies')
    # ### end Alembic commands ###
