"""add intensity to isotope_decay_energies

Revision ID: db80d607e393
Revises: 9ca472d287a3
Create Date: 2026-07-31 17:27:34.157064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db80d607e393'
down_revision: Union[str, None] = '9ca472d287a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('isotope_decay_energies', sa.Column('intensity', sa.Float(), nullable=True))
    op.add_column('isotope_decay_energies', sa.Column('intensity_error', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('isotope_decay_energies', 'intensity_error')
    op.drop_column('isotope_decay_energies', 'intensity')
    # ### end Alembic commands ###
